---
name: Compile C++

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'

jobs:

  FileList:
    outputs:
      filelist: ${{ steps.get-files.outputs.filelist }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output with list of files
        id: get-files
        run: |
          import glob, json, os
          files = glob.glob("**/tests/*.cpp")
          print("::set-output name=filelist::{}".format(json.dumps(files)))
        shell: python
      - name: Display output
        run: echo ${{ steps.get-files.outputs.filelist }}

  Compile:
    runs-on: ubuntu-latest
    needs: [FileList]
    strategy:
      matrix:
        file: ${{ fromJson(needs.FileList.outputs.filelist) }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v11
      - name: Install CPP compiler
        uses: rlalik/setup-cpp-compiler@v1.1
        with:
          compiler: gcc-latest
      - name: Compile ${{ matrix.file }} via emcc
        run: emcc "${{ matrix.file }}"
      - name: Compile ${{ matrix.file }} via g++
        run: g++ -c "${{ matrix.file }}"
