---
name: Compile MQL

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/workflows/compile-mql.yml'
  push:
    paths-ignore:
      - '**.md'
      - '.github/workflows/compile-mql.yml'

jobs:

  Compile-MQL:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile
        uses: fx31337/mql-compile-action@master
        with:
          init-platform: true
          verbose: true
      - name: Print compiled files
        run: '(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname'
        shell: powershell
