---
name: Compile C++

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/workflows/compile-cpp.yml'
  push:
    paths-ignore:
      - '**.md'
      - '.github/workflows/compile-cpp.yml'

jobs:

  Compile-Cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install CPP compiler
        uses: rlalik/setup-cpp-compiler@v1.1
        with:
          compiler: gcc-latest
      - name: Compile via make
        run: make
  Compile-Emscripten:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v11
      - name: Compile via emcc
        run: make CC=emcc
