---
name: Test Indicators (OHLC)

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - 'Indicator/**'
      - 'Indicators/OHLC/**'
      - '.github/workflows/test-indicators-special.yml'
  push:
    paths:
      - 'Indicator/**'
      - 'Indicators/OHLC/**'
      - '.github/workflows/test-indicators-special.yml'

jobs:

  compile:
    name: Compile
    uses: ./.github/workflows/compile-mql.yml
    with:
      artifact_prefix: mt
      path: Indicators/OHLC/tests
      skip_cleanup: true

  Tests-MQL4:
    defaults:
      run:
        shell: bash
        working-directory: Indicators/OHLC/tests
    if: false
    needs: compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - Indi_OHLC.test
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: files-ex4
      - name: Run ${{ matrix.test }}
        uses: fx31337/mql-tester-action@master
        with:
          BtDays: 4-8
          BtMonths: 1
          BtYears: 2021
          GitHubApiToken: ${{ github.token }}
          RunOnError: show_logs 200
          TestExpert: ${{ matrix.test }}
    timeout-minutes: 10
