---
name: Test Platform

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - 'Platform/Chart3D/**'
      - '.github/workflows/test-platform-chart3d.yml'
  push:
    paths:
      - 'Platform/Chart3D/**'
      - '.github/workflows/test-platform-chart3d.yml'

jobs:

  compile:
    name: Compile
    uses: ./.github/workflows/compile-mql.yml
    with:
      artifact_prefix: mt
      path: Platform/Chart3D/tests
      skip_cleanup: true

  Tests-MQL4:
    defaults:
      run:
        shell: bash
        working-directory: Platform/Chart3D/tests
    if: false
    needs: compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - Chart3D.test
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: files-ex4
      - name: Run ${{ matrix.test }}
        uses: fx31337/mql-tester-action@master
        with:
          Script: ${{ matrix.test }}
    timeout-minutes: 10
