---
name: Test Indicators (Tick)

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - 'Indicator**'
      - 'Indicators/Tick/**'
      - '.github/workflows/test-indicators-tick.yml'
  push:
    paths:
      - 'Indicator**'
      - 'Indicators/Tick/**'
      - '.github/workflows/test-indicators-tick.yml'

jobs:

  compile:
    name: Compile
    uses: ./.github/workflows/compile.yml
    with:
      artifact_prefix: mt
      skip_cleanup: true

  Indicators-Tests-MQL4:
    defaults:
      run:
        shell: bash
        working-directory: Indicators/tests
    if: false
    needs: compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - Indi_Tick.test
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: files-ex4
      - name: Run ${{ matrix.test }}
        uses: fx31337/mql-tester-action@master
        with:
          BtDays: 4-8
          BtMonths: 1
          BtYears: 2020
          TestExpert: ${{ matrix.test }}
    timeout-minutes: 10
