---
name: Test Exchange/Account

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - 'Exchange/Account/**'
      - '.github/workflows/test-exchange/account.yml'
  push:
    paths:
      - 'Exchange/Account/**'
      - '.github/workflows/test-exchange/account.yml'

jobs:

  compile:
    name: Compile
    uses: ./.github/workflows/compile-mql.yml
    with:
      artifact_prefix: mt
      path: Exchange/Account/tests
      skip_cleanup: true

  Tests-MQL4:
    defaults:
      run:
        shell: bash
        working-directory: Exchange/Account/tests
    if: false
    needs: compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - Account.test
          - AccountForex.test
          - AccountMt.test
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: files-ex4
      - name: Run ${{ matrix.test }}
        uses: fx31337/mql-tester-action@master
        with:
          Script: ${{ matrix.test }}
    timeout-minutes: 10

  cleanup:
    name: Clean-up
    needs: [compile]
    uses: ./.github/workflows/cleanup.yml
