---
name: Test Indicators

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - 'Indicator**'
      - 'Indicators/**'
      - '.github/workflows/test-indicators.yml'
  push:
    paths:
      - 'Indicator**'
      - 'Indicators/**'
      - '.github/workflows/test-indicators.yml'

jobs:

  compile:
    name: Compile
    uses: ./.github/workflows/compile.yml
    with:
      artifact_prefix: mt
      skip_cleanup: true

  Indicators-Tests-MQL4:
    defaults:
      run:
        shell: bash
        working-directory: Indicators/tests
    if: false
    needs: compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - Indi_AC.test
          - Indi_AD.test
          - Indi_ADX.test
          - Indi_ADXW.test
          - Indi_AMA.test
          - Indi_AO.test
          - Indi_ASI.test
          - Indi_ATR.test
          - Indi_Alligator.test
          - Indi_AppliedPrice.test
          - Indi_BWMFI.test
          - Indi_BWZT.test
          - Indi_Bands.test
          - Indi_BearsPower.test
          - Indi_BullsPower.test
          - Indi_CCI.test
          - Indi_CHO.test
          - Indi_CHV.test
          - Indi_ColorBars.test
          - Indi_ColorCandlesDaily.test
          - Indi_ColorLine.test
          - Indi_CustomMovingAverage.test
          - Indi_DEMA.test
          - Indi_DeMarker.test
          - Indi_Demo.test
          - Indi_DetrendedPrice.test
          - Indi_Drawer.test
          - Indi_Envelopes.test
          - Indi_Force.test
          - Indi_FractalAdaptiveMA.test
          - Indi_Fractals.test
          - Indi_Gator.test
          - Indi_HeikenAshi.test
          - Indi_Ichimoku.test
          - Indi_Killzones.test
          - Indi_MA.test
          - Indi_MACD.test
          - Indi_MFI.test
          - Indi_MassIndex.test
          - Indi_Momentum.test
          - Indi_OBV.test
          - Indi_OHLC.test
          - Indi_OsMA.test
          - Indi_Pattern.test
          - Indi_Pivot.test
          - Indi_Price.test
          - Indi_PriceChannel.test
          - Indi_PriceFeeder.test
          - Indi_PriceVolumeTrend.test
          - Indi_RS.test
          - Indi_RSI.test
          - Indi_RVI.test
          - Indi_RateOfChange.test
          - Indi_SAR.test
          - Indi_StdDev.test
          - Indi_Stochastic.test
          - Indi_TEMA.test
          - Indi_TRIX.test
          - Indi_UltimateOscillator.test
          - Indi_VIDYA.test
          - Indi_VROC.test
          - Indi_Volumes.test
          - Indi_WPR.test
          - Indi_WilliamsAD.test
          - Indi_ZigZag.test
          - Indi_ZigZagColor.test
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: files-ex4
      - name: Run ${{ matrix.test }}
        uses: fx31337/mql-tester-action@master
        with:
          BtDays: 4-8
          BtMonths: 1
          BtYears: 2020
          TestExpert: ${{ matrix.test }}
    timeout-minutes: 10
