---
name: Test Storage

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - 'Storage/**'
      - '.github/workflows/test-storage.yml'
  push:
    paths:
      - 'Storage/**'
      - '.github/workflows/test-storage.yml'

jobs:

  compile:
    name: Compile
    uses: ./.github/workflows/compile.yml
    with:
      artifact_prefix: mt
      path: Exchange
      skip_cleanup: true

  Storage-Tests-MQL4:
    defaults:
      run:
        shell: bash
        working-directory: Storage/tests
    if: false
    needs: compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - Collection.test
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: files-ex4
      - name: Run ${{ matrix.test }}
        uses: fx31337/mql-tester-action@master
        with:
          Script: ${{ matrix.test }}
