---
name: Test Platform/Web

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - 'Platform/Web/**'
      - '.github/workflows/test-platform-web.yml'
  push:
    paths:
      - 'Platform/Web/**'
      - '.github/workflows/test-platform-web.yml'

jobs:

  compile:
    name: Compile
    uses: ./.github/workflows/compile-mql.yml
    with:
      artifact_prefix: mt
      path: Platform/Web/tests
      skip_cleanup: true

  Tests-MQL4:
    defaults:
      run:
        shell: bash
        working-directory: Platform/Web/tests
    if: false
    needs: compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          # @fixme: GH-266
          - Web.test
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: files-ex4
      - name: Run ${{ matrix.test }}
        uses: fx31337/mql-tester-action@master
        with:
          Script: ${{ matrix.test }}
          RunOnFail: "exit 0"
        if: always()
    timeout-minutes: 10
