---
name: Test Storage/Cache

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - 'Storage/Cache/**'
      - '.github/workflows/test-storage-cache.yml'
  push:
    paths:
      - 'Storage/Cache/**'
      - '.github/workflows/test-storage-cache.yml'

jobs:

  compile:
    name: Compile
    uses: ./.github/workflows/compile-mql.yml
    with:
      artifact_prefix: mt
      path: Storage/Cache/tests
      skip_cleanup: true

  Tests-MQL4:
    defaults:
      run:
        shell: bash
        working-directory: Storage/Cache/tests
    if: false
    needs: compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - IndiBufferCache.test
          - ObjectsCache.test
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: files-ex4
      - name: Run ${{ matrix.test }}
        uses: fx31337/mql-tester-action@master
        with:
          Script: ${{ matrix.test }}
          RunOnError: show_logs 200
    timeout-minutes: 10

  cleanup:
    name: Clean-up
    needs: [compile]
    uses: ./.github/workflows/cleanup.yml
