---
name: Test Indicators

env:
  TEST_PATH: Indicators/tests
  TEST_SKIP: ${{ secrets.MT5_LOGIN || false }}

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - .github/workflows/test-indicators.yml
      - Indicator**
      - Indicators/**
  push:
    paths:
      - .github/workflows/test-indicators.yml
      - Indicator**
      - Indicators/**

jobs:

  compile:
    name: Compile
    uses: ./.github/workflows/compile-mql.yml
    with:
      artifact_prefix: mt
      path: Indicators/tests
      skip_cleanup: true

  test:
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TEST_PATH }}
    name: Test
    needs: compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - DrawIndicator.test
          - Indi_AC.test
          - Indi_AD.test
          - Indi_ADX.test
          - Indi_ADXW.test
          - Indi_AMA.test
          - Indi_AO.test
          - Indi_ASI.test
          - Indi_ATR.test
          - Indi_BWMFI.test
          - Indi_BWZT.test
          - Indi_BearsPower.test
          - Indi_BullsPower.test
          - Indi_CCI.test
          - Indi_CHO.test
          - Indi_CHV.test
          - Indi_DeMarker.test
          - Indi_Demo.test
          - Indi_DetrendedPrice.test
          - Indi_Drawer.test
          - Indi_Force.test
          - Indi_FractalAdaptiveMA.test
          - Indi_Fractals.test
          - Indi_Gator.test
          - Indi_HeikenAshi.test
          - Indi_Ichimoku.test
          - Indi_Killzones.test
          - Indi_MFI.test
          - Indi_MassIndex.test
          - Indi_Momentum.test
          - Indi_OBV.test
          - Indi_OsMA.test
          - Indi_PriceChannel.test
          - Indi_PriceFeeder.test
          - Indi_PriceVolumeTrend.test
          - Indi_RS.test
          - Indi_RVI.test
          - Indi_RateOfChange.test
          - Indi_StdDev.test
          - Indi_TEMA.test
          - Indi_TRIX.test
          - Indi_UltimateOscillator.test
          - Indi_VIDYA.test
          - Indi_VROC.test
          - Indi_Volumes.test
          - Indi_WilliamsAD.test
          - Indi_ZigZag.test
          - Indi_ZigZagColor.test
          - Indicators.test
          # Requires refactoring:
          # - Indi_DEMA.test
        version: [5]
      max-parallel: 4
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: files-ex${{ matrix.version }}
      - name: List compiled files
        run: find . -name '*.ex?' -type f -print
      - if: ${{ env.TEST_SKIP != true }}
        name: Run ${{ matrix.test }}
        uses: fx31337/mql-tester-action@master
        with:
          Login: ${{ secrets.MT5_LOGIN }}
          Password: ${{ secrets.MT5_PASSWORD }}
          Server: MetaQuotes-Demo
          TestDeposit: 2000
          TestExpert: ${{ matrix.test }}
          TestFromDate: ${{ matrix.year }}.01.01
          TestPeriod: M1
          TestSymbol: EURUSD
          TestToDate: ${{ matrix.year }}.01.14
          # yamllint disable-line rule:line-length
          UrlExpert: file://${{ github.workspace }}/${{ env.TEST_PATH }}/${{ matrix.test }}.ex${{ matrix.version }}
          Version: 5
      - if: ${{ failure() && runner.debug == '1' }}
        uses: mxschmitt/action-tmate@v3
    timeout-minutes: 20

  cleanup:
    name: Clean-up
    needs: [compile]
    uses: ./.github/workflows/cleanup.yml
